let stockProductos = [
    {id: 1, nombre: "iPhone 11", tipo: "smartphone", cantidad: 1, precio: 500, img: '../img/11.jpg'},
    {id: 2, nombre: "iPhone 11", tipo: "smartphone", cantidad: 1, precio: 500, img: '../img/11.jpg'},
    {id: 3, nombre: "iPhone 11", tipo: "smartphone", cantidad: 1, precio: 500, img: '../img/11.jpg'},
    {id: 4, nombre: "iPhone 11", tipo: "smartphone", cantidad: 1, precio: 500, img: '../img/11.jpg'},
    {id: 5, nombre: "iPhone 12", tipo: "smartphone", cantidad: 1, precio: 650, img: '../img/12.jpg'},
    {id: 6, nombre: "iPhone 12", tipo: "smartphone", cantidad: 1, precio: 650, img: '../img/12.jpg'},
    {id: 7, nombre: "iPhone 12", tipo: "smartphone", cantidad: 1, precio: 650, img: '../img/12.jpg'},
    {id: 8, nombre: "iPhone 12", tipo: "smartphone", cantidad: 1, precio: 650, img: '../img/12.jpg'},
    {id: 9, nombre: "iPhone 12 Pro", tipo: "smartphone", cantidad: 1, precio: 950, img: '../img/12pro.jpg'},
    {id: 10, nombre: "iPhone 12 Pro", tipo: "smartphone", cantidad: 1, precio: 950, img: '../img/12pro.jpg'},
    {id: 11, nombre: "iPhone 12 Pro", tipo: "smartphone", cantidad: 1, precio: 950, img: '../img/12pro.jpg'},
    {id: 12, nombre: "iPhone 12 Pro", tipo: "smartphone", cantidad: 1, precio: 950, img: '../img/12pro.jpg'},
    {id: 13, nombre: "iPhone 13", tipo: "smartphone", cantidad: 1, precio: 1000, img: '../img/13.jpg'},
    {id: 14, nombre: "iPhone 13", tipo: "smartphone", cantidad: 1, precio: 1000, img: '../img/13.jpg'},
    {id: 15, nombre: "iPhone 13", tipo: "smartphone", cantidad: 1, precio: 1000, img: '../img/13.jpg'},
    {id: 16, nombre: "iPhone 13", tipo: "smartphone", cantidad: 1, precio: 1000, img: '../img/13.jpg'},
    {id: 17, nombre: "iPhone 13 Pro", tipo: "smartphone", cantidad: 1, precio: 1150, img: '../img/13pro.jpg'},
    {id: 18, nombre: "iPhone 13 Pro", tipo: "smartphone", cantidad: 1, precio: 1150, img: '../img/13pro.jpg'},
    {id: 19, nombre: "iPhone 13 Pro", tipo: "smartphone", cantidad: 1, precio: 1150, img: '../img/13pro.jpg'},
    {id: 20, nombre: "iPhone 13 Pro", tipo: "smartphone", cantidad: 1, precio: 1150, img: '../img/13pro.jpg'},
]